.github/workflows/vul.yml

I fixed (trivial) the case for Windows tests from https://github.com/KhronosGroup/Vulkan-Utility-Libraries/pull/5

Add GitHub actions

---

.github/workflows/vul.yml
BUILD.md
CMakeLists.txt
layer_utils/CMakeLists.txt
scripts/CMakeLists.txt

Allows build options specific to Vulkan-Utility-Libraries to be easily grouped via cmake-gui.
This approach is also nicer for users who consume the library via add_subdirectory or FetchContent since it more obvious what settings are being ovverriden.
Remove UTILITY_LIBRARIES_CPP_STANDARD since we don't have a reason to support multiple CPP standards.
Set testing to OFF by default to make consuming the library easier for users and package managers.

cmake: Use VUL_ prefix for cache variables

---

include/vulkan/layer/vk_layer_settings_ext.h
src/layer/layer_settings_manager.cpp
src/layer/layer_settings_manager.hpp
src/layer/vk_layer_settings.cpp
tests/layer/test_setting_api.cpp

Bbasically move the content of `VkLayerSettingDataEXT` into `VkLayerSettingEXT` to streamline the layer setting API

layer: streamline setting data API

---

src/layer/layer_settings_util.hpp

The validation layer linux build is failing here: https://github.com/KhronosGroup/Vulkan-ValidationLayers/actions/runs/5061899634/jobs/9086732563?pr=5897
This resolve this issue.

layer: fix linux build

---

include/vulkan/layer/vk_layer_settings.h
include/vulkan/layer/vk_layer_settings_ext.h
src/layer/layer_settings_manager.cpp
src/layer/layer_settings_manager.hpp
src/layer/layer_settings_util.cpp
src/layer/vk_layer_settings.cpp
tests/layer/test_setting_api.cpp
tests/layer/test_setting_util.cpp

The validation layer is already using VK_STRUCTURE_TYPE_INSTANCE_LAYER_SETTINGS_EXT with a specific value. We need a different value and name to avoid the layer setting library to interpret some structure which are specificed differently causing a segfault.

layer: avoid conflict with validation layer setting extension

---

src/layer/layer_settings_manager.cpp

This is causign an issue for layer expecting setting values with a specific case.

layer: setting values converted to lower case

---

src/layer/layer_settings_util.cpp
src/layer/vk_layer_settings.cpp

I noticed this when trying to build Vulkan-Profiles with GCC on Fedora 38. It is likely the same problem is present in the validation layers if it is also using this library now.

build: Fix build errors on GCC 13

---

include/vulkan/layer/vk_layer_settings.h
src/layer/layer_settings_manager.cpp
src/layer/layer_settings_manager.hpp
src/layer/vk_layer_settings.cpp
tests/add_subdirectory/client.c
tests/layer/test_setting_api.cpp
tests/layer/test_setting_file.cpp

Currently a layer can only rely on a single set of layers settings because the layer settings library hide a singleton. This makes handling multiple instances with different settings impossible.
To resolve this issue we create a new object that actually store the layer settings and which memory it handle externally, by the layer, replacing the hidden singleton.

layer: add layer setting set to handle multiple instances

---

BUILD.gn
src/layer/vk_layer_settings.cpp

- Static library
- Add overrides, not necessary yet but it will be when other parts of this repo wants to find Vulkan-Headers
- Remove unused dependency on Vulkan-Headers from the settings library
- Remove unreachable return flagged by clang
Feel free to just squash this into your branch

Get GN build working

---

include/vulkan/vk_enum_string_helper.h
scripts/generators/enum_string_helper_generator.py
tests/add_subdirectory/CMakeLists.txt
tests/add_subdirectory/vk_enum_string_helper.c
tests/find_package/CMakeLists.txt
tests/generated/vk_enum_string_helper.cpp

Added ifdef checks for backcompat
Intended to properly address these issue(s):
- https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3233
- https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/1211

tests: Ensure vk_enum_string_helper.h is C compatible

---

include/vulkan/vk_enum_string_helper.h
scripts/generators/enum_string_helper_generator.py

Not needed. They only made sense in the context of VVL.

Remove clang-tidy comments from vk_enum_string_helper.h

---

BUILD.gn

You must specify header files in a GN build

Fix gn build

---

include/vulkan/utility/.clang-format
include/vulkan/utility/vul_dispatch_table.h
scripts/generators/dispatch_table_generator.py

The code did not follow the provided clang-format file, which causes conflict when a developer runs clang-format on the repo. This commit fixes the generator so that the output is what clang-format would generate. One issue is that clang-format's ColumnLimit will wrap long lines, and is very difficult to replicate in python code without excessive changes. The chosen solution is to use a custom clang-format file for the Utilities folder which ignores the ColumnLimit.

headers: Fix dispatch table formatting

---

BUILD.gn

This seems obvious in hindsight, but the linux build I initially tested with never required it. It is absolutely required for most of the other platforms though.

build: Add header dependency to GN build

---

src/layer/layer_settings_manager.cpp
tests/layer/test_setting_env.cpp

A setting can be accessed using env variables using the following order:
`VK_LUNARG_TEST_MY_SETTING`
`VK_TEST_MY_SETTING`
`VK_MY_SETTING`
`VK_MY_SETTING` mode was not working.

layer: Fix env variable trim modes

---

src/layer/layer_settings_manager.cpp

Found in VVL integration build: https://github.com/KhronosGroup/Vulkan-ValidationLayers/actions/runs/6089851914/job/16523507417?pr=6426
```
FAILED: obj/external/Vulkan-Utility-Libraries/vulkan_layer_settings/layer_settings_manager.o 
../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/external/Vulkan-Utility-Libraries/vulkan_layer_settings/layer_settings_manager.o.d -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_OZONE=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_GNU_SOURCE -DCR_CLANG_REVISION=\"llvmorg-16-init-17653-g39da55e8-2\" -DCOMPONENT_BUILD -DCR_SYSROOT_KEY=20221105T211506Z-0 -D_DEBUG -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DVK_USE_PLATFORM_XCB_KHR -I../.. -Igen …
```

Fix -Wshadow warning

---

BUILD.gn
include/CMakeLists.txt
include/vulkan/utility/vk_format_utils.h
scripts/generate_source.py
scripts/generators/format_utils_generator.py
tests/CMakeLists.txt
tests/add_subdirectory/CMakeLists.txt
tests/add_subdirectory/vk_format_utils.c
tests/add_subdirectory/vk_format_utils_2.c
tests/find_package/CMakeLists.txt
tests/format_utils/CMakeLists.txt
tests/format_utils/test_formats.cpp

The library originates from Vulkan-ValidationLayers, but is being moved into this repo to make it easier for others to use it.
The library has also been modified to be header only and C compatible, which allows more developers to be able to use it. This does require some changes, but only affects the FormatElementSize and FormatTexelSize functions which used default parameters. Two new functions, FormatElementSizeWithAspect and FormatTexelSizeWithAspect have been added to handle the non-default image aspect case (the default was COLOR_BIT).

src: Add vk_format_utils to UtilityHeaders

---

src/layer/vk_layer_settings.cpp

The layer code using vlGetUnknownSettings doesn't need to check pCreateInfo is null or not, that considition is resolve in the function as it gives a meaningful result: When no setting is set then this is no unknown setting

layer: Simplify code using vkGetUnknownSettings

---

include/vulkan/layer/vk_layer_settings.h
include/vulkan/layer/vk_layer_settings.hpp
src/layer/layer_settings_manager.cpp
src/layer/layer_settings_manager.hpp
src/layer/vk_layer_settings.cpp
src/layer/vk_layer_settings_helper.cpp
tests/layer/test_setting_api.cpp
tests/layer/test_setting_util.cpp

This PR is the product of VK_EXT_layer_settings spec review, discussing the use case of overriding layer settings from other layers for example without having to rebuilt the structure.

layer: Add multiple VkLayerSettingsCreateInfo support

---

include/vulkan/utility/vk_struct_helper.hpp
scripts/generators/struct_helper_generator.py

Some compilers complain about this.

Remove extra semicolon after member definition

---

CMakeLists.txt
include/CMakeLists.txt
scripts/CMakeLists.txt
src/CMakeLists.txt
src/layer/CMakeLists.txt
src/layer/layer_settings_manager.cpp
src/layer/layer_settings_util.cpp
src/layer/vk_layer_settings.cpp
tests/find_package/CMakeLists.txt
tests/generated/CMakeLists.txt
tests/layer/CMakeLists.txt
tests/vk_dispatch_table/CMakeLists.txt

Also fixes issue where compiler warnings weren't being applied to `Vulkan::LayerSettings`
closes #106

 cmake: Export library to standardize compiler/linker options 

---

src/CMakeLists.txt

You can use MSVC, clang, or clang-cl on Windows.

Fixes Clang on Windows build

---

include/vulkan/utility/vk_format_utils.h
scripts/generators/format_utils_generator.py

Now the documentation matches the implementation.

Fix doc for vkuFormatIsXChromaSubsampled

---

include/vulkan/utility/vk_struct_helper.hpp
scripts/generators/base_generator.py
scripts/generators/struct_helper_generator.py
tests/struct_helper/struct_helper.cpp

This utility converst Vulkan handle types to VkObjectType enums, which is used
by the debug utils set name & tag functions.
The logic for vendorTags didn't correctly iterate through the children of tags,
causing the vendorTags list to be generated incorrectly.

Add GetObjectType helper to struct_helper and Fix base_generator vendorTags logic

---

CMakeLists.txt
scripts/CMakeLists.txt
scripts/generate_source.py
scripts/generators/base_generator.py
scripts/known_good.json

This is the now familiar API parameterization changes that will be needed also for VUL.
All of the changes mimic to what is/was there in the VVL code for these before they were moved to VUL.

build: API parameterization

---

include/vulkan/utility/vk_struct_helper.hpp
scripts/generators/struct_helper_generator.py

Non Dispatchable handles are not typed in 32 bit builds, so the vku::GetObjectHandle() helper fails to compile. The solution is to just not define the helper in 32 bit builds.

util: Fix vku::GetObjectType() broken for 32 bit builds

---

.github/dependabot.yml
.github/workflows/ci.yml

Ensures actions are kept up to date
Update ci.yml to not create duplicate workflow when dependabot creates branches on the repo

ci: Add dependabot

---

tests/test_setting_env.cpp

Need to unset an env-var in order to allow the vul_tests executable to pass all tests. This is because environment variables leak between tests when not running with CTest.

Unset env-var in layer tests

---

src/layer/layer_settings_util.cpp

Vulkan-Profiles layer (and possibly other users of the library) is not working correctly on Android, due to multiple point symbols added for the environment variable checks. This CL removes the unnecessary '.' character to fix the issue.

Fix default env setting prefix for Android

---

CMakeLists.txt
tests/integration/CMakeLists.txt

VulkanUtilityLibrariesConfig.cmake will now find VulkanHeaders for the user.

cmake: Improve packaging

---

CMakeLists.txt

This fixes the problem whereas in the generated `VulkanUtilityLibrariesConfig.cmake` the value of `PACKAGE_PREFIX_DIR` may get overwritten by the `VulkanHeaders` discovery process.

build: Make find_package logic more robust

---

scripts/generators/base_generator.py

found during https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7204
things like `VkDisplayModeKHR` were not being marked as `instance` due to having a chain of `VkPhysicalDevice`->`VkInstance`

scripts: Sync base_generator.py

---

scripts/generators/base_generator.py

syncing change from https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7355

scripts: Add struct extension re-lookup in base generator

---

include/vulkan/utility/vk_struct_helper.hpp
include/vulkan/vk_enum_string_helper.h
scripts/known_good.json

build: Update to header 1.3.278

---

scripts/gn/gn.py

Just like VVL, it was using subprocess.call(), which ignores errors.

scripts: Make gn.py use check_call

---

scripts/generate_source.py

This matches the `--target` functionality to take in multiple files that we have in validation layers

scripts: Update generate_source.py to take mulitple targets

---

scripts/generators/safe_struct_generator.py
src/vulkan/vk_safe_struct_vendor.cpp

QNX platform types should be considered abstract. We want to use the flow of just "saving the pointer away" instead of making a copy.

safestruct: Add QNX platform types to abstract_types list

---

include/vulkan/utility/vk_safe_struct.hpp
scripts/generators/safe_struct_generator.py
src/vulkan/vk_safe_struct_ext.cpp
src/vulkan/vk_safe_struct_manual.cpp

Revert #196
VkDescriptorDataEXT needs to be safe.
When running with validation layers the CTS test `dEQP-VK.binding_model.descriptor_buffer.single.graphics_vert_sampled_image` and other descriptor buffer tests crash after the tests finish. 
If `VkDescriptorDataEXT` is not safe, then in `layer_chassis_dispatch_manual.cpp` in function `DispatchGetDescriptorEXT()` the descriptors are overwritten with the unwrapped handles, because `local_pDescriptorInfo.data` has the same pointers as `pDescriptorInfo->data`, and when tests finish the invalid unwrapped handles are used to delete the descriptors (sampler is this case), which leads to:
```
Test case 'dEQP-VK.binding_model.descriptor_buffer.single.graphics_vert_sampled_image'..
VUID-vkDestroySampler-sampler-parameter(ERROR / SPEC): msgNum: …
```

Revert "safestruct: Remove safe_VkDescriptorDataEXT"

---

src/vulkan/vk_safe_struct_manual.cpp

will fix https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7899 when pulled in
If you are using `VK_DYNAMIC_STATE_RASTERIZER_DISCARD_ENABLE_EXT` it should be setting `has_rasterization` to true as we assume it is until decided later

scripts: Fix Pipeline dynamic rasterization discard logic

---

src/vulkan/vk_safe_struct_manual.cpp

this is for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5931
The logic is https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5932 was close, but needed both https://github.com/KhronosGroup/Vulkan-Utility-Libraries/commit/68780d9b8c4dd256e55a3df60969970cb29911ce and be adjusted for pipeline libraries
Was tested with CTS and new tests

scripts: Fix logic for ignoring pipe state

---

src/vulkan/vk_safe_struct_manual.cpp

For https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8015
FINALLY think we got this right
The Renderpass and Fragment shader have nothing to do with `pMultisampleState`
This is done at Rasterization time, and the only thing that matter is `has_rasterization` (or if Graphics Pipeline Library... because is guarded elsewhere)

safestruct: Fix pMultisampleState

---

CMakeLists.txt
scripts/generate_source.py

In order to avoid having to deal with mixed generated vs manual sources / headers in this repo, we decided to not maintain separate source trees at all for API variants downstream, so this change removes the existing path parameterizations based on the target API variant.

build: Do not specialize source tree for API variants

---

.gitignore
include/vulkan/utility/vk_struct_helper.hpp
scripts/generators/struct_helper_generator.py

Create a new default specialization for 32 bit which indicates to the
user that the GetObjectType() helper does not work in 32 bit builds.

Better declare GetObjectType()'s lack of 32 bit support

---

include/vulkan/utility/vk_safe_struct.hpp
include/vulkan/utility/vk_safe_struct_utils.hpp
scripts/generators/safe_struct_generator.py
src/vulkan/vk_safe_struct_manual.cpp
src/vulkan/vk_safe_struct_utils.cpp

Adding Tracy in VVL showed that we are paying the price of initializing global variables upon shared library entry, even if we do not end up accessing those.
Adding accessors will make sure we pay this price
only when truly needed.
Also making the necessary changes in VVL.

safestruct: Accessors for non trivial globals

---

include/vulkan/utility/vk_safe_struct.hpp
scripts/generators/safe_struct_generator.py
src/vulkan/vk_safe_struct_ext.cpp

fixes https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8388 (confirmed with test )

safe: Fix VK_EXT_sample_locations

---

tests/safe_struct.cpp
tests/sparse_range_map.cpp
tests/struct_helper.cpp
tests/test_formats.cpp
tests/test_interface.cpp
tests/test_setting_api.cpp
tests/test_setting_cast.cpp
tests/test_setting_cpp.cpp
tests/test_setting_env.cpp
tests/test_setting_file.cpp
tests/test_setting_util.cpp

With latest visual studio, there are a lot of new warnings about comparing mismatched types

tests: Fix windows warnings

---

src/layer/layer_settings_manager.cpp

Modify the function for getting system properties on Android: 
*Use the new __system_property_read_callback API that appeared in Android O / API level 26 when available. It is the preferred way because it allows handling long property names and better property caching. 
*When not available use the deprecated __system_property_get function.

Fix usage of __system_property_read_callback for Android<26

---

.github/workflows/ci.yml

Prevents wasting CI minutes on builds that will fail early on something obvious

ci: Build dependency for Github Actions

---

scripts/generate_source.py

Allow the registry path argument to also be the base directory containing the Vulkan-Headers repo (eg. ./external) to save redundant typing.

scripts: Make generate_source.py look harder for vk.xml

---

src/vulkan/vk_safe_struct_manual.cpp

Partial fix for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8693

Traverse geometry pNext for safe structs

---

include/vulkan/layer/vk_layer_settings.hpp
include/vulkan/utility/vk_concurrent_unordered_map.hpp
scripts/generators/safe_struct_generator.py
src/layer/vk_layer_settings.cpp
src/vulkan/vk_safe_struct_core.cpp
src/vulkan/vk_safe_struct_ext.cpp
src/vulkan/vk_safe_struct_khr.cpp
src/vulkan/vk_safe_struct_vendor.cpp

This is to fix build error when we set use_libcxx_modules=true in chromium build.

build: Add missing include headers

---

include/vulkan/utility/vk_format_utils.h
scripts/generators/format_utils_generator.py

as discussed in https://gitlab.khronos.org/vulkan/vulkan/-/issues/4144#note_511349 there is a difference between "Multi-planar" and "Requires Sampler Y′CBCR Conversion"
We do it right here, but just adding a note for the next person who second-guesses themselves

format: Add note for Multi-planar

---

include/vulkan/utility/vk_format_utils.h
scripts/generators/format_utils_generator.py
tests/test_formats.cpp

This `vkuFormatElementIsTexel` is a bad, misleading function
1. There is no concept of "elements" for texel in the Vulkan Spec (https://gitlab.khronos.org/vulkan/vulkan/-/issues/4109)
2. This is only used in a single VVL check for deciding if the Vertex attribute should be divided or not (which still not sure if doing correctly or not)
Basically there is no valid spec language backing this function up and if someone "really" needs it, they can manually do the check this is removing (which I am still convinced is not fully correct)

formats: Remove vkuFormatElementIsTexel

---

include/vulkan/utility/vk_format_utils.h
scripts/generators/format_utils_generator.py
tests/test_formats.cpp

Adds `vkuFormatIsDepthStencilWithColorSizeCompatible`
`VK_KHR_maintenance8` added this and now have ability to detect which color and depth/stencil formats are able to be together

formats: Add vkuFormatIsDepthStencilWithColorSizeCompatible

---

include/vulkan/utility/vk_format_utils.h
scripts/generators/format_utils_generator.py
tests/integration/vk_format_utils.c
tests/integration/vk_format_utils_2.c
tests/test_formats.cpp

`Element` is not a real spec term, it is a `Texel` inside a `Texel Block`
This adds `vkuFormatTexelBlockSize` and deprecates `vkuFormatElementSize`/`vkuFormatElementSizeWithAspect` as they should not be used.
The core issues is there are various places (like vertex inputs) where we use Formats and want the texel block size, but we don't actually need to care about if it is depth/stencil/mult-planar because  its not even allowed.... Basically people should use the utils to get the `Texel Block` size and then adjust it depending on the use case

formats: Add vkuFormatTexelBlockSize

---

include/vulkan/utility/vk_format_utils.h
scripts/generators/format_utils_generator.py
tests/test_formats.cpp

Adds `vkuFormatTexelsPerBlock` - we had to proper way to get the `texels_per_block` generated

formats: Add vkuFormatTexelsPerBlock

---

CMakeLists.txt

The actual CMake minimum version bump occurred in a header update, this just makes use of the new features in 3.22.

Update cmake to 3.22

---

src/layer/layer_settings_manager.cpp

* As of r28, some unguarded calls now generate `-Wunguarded-availability`
* Change class to be guarded by ifdefs
This was caught during our internal rollout of r28

Add additional Android NDK API guards

---

include/vulkan/utility/vk_format_utils.h
scripts/generators/format_utils_generator.py
tests/test_formats.cpp

for https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/9588
I completely messed up and forgot the stencil aspect mask case for something like `VK_FORMAT_D32_SFLOAT_S8_UINT` is different formats

format: Fix DepthStencil to Color compatible check

---

scripts/generators/format_utils_generator.py

This is to make sure when https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/7257 is merged, this won't mess up the `vkuFormatIsSRGB` function

formats: Handle SRGB correction

---

CMakeLists.txt
include/vulkan/utility/vk_safe_struct_utils.hpp

Calling memcpy with either src or dst as nullptr is undefined even if the count is 0.
Discovered by running tests with -fsanitize=undefined
safe_struct.extension_add_remove specifcially

Fix UBSAN error

---

include/vulkan/utility/vk_format_utils.h
scripts/generators/format_utils_generator.py
tests/test_formats.cpp

The `vkuFormatElementSize`/`vkuFormatTexelSize` should not be used
If people want to do it themselves, they should as it requires so REAL consideration to find the size of format that is a color vs depth/stencil vs compressed
More information on how "sizes" is calculated please reference https://github.com/KhronosGroup/Vulkan-Guide/blob/main/chapters/image_copies.adoc

formats: Remove old format utils

---

src/layer/layer_settings_manager.cpp
tests/test_setting_env.cpp

This resolve the issue with the validation layer:
```
VK_LAYER_THREAD_SAFETY - Sets it ✅
VK_THREAD_SAFETY - doesn't ❌
VK_VALIDATION_THREAD_SAFETY - Sets it ✅
VK_KHRONOS_VALIDATION_THREAD_SAFETY - Sets it ✅
```
`VK_THREAD_SAFETY` was not working because the validation layer has a backward compatiblity namespace and they where a bug here.

layer: Fix trim namespace env with overridden namespace

---

CMakeLists.txt

The top-level CMakeLists.txt file finds the VulkanHeaders package with the version CMAKE_PROJECT_VERSION. This works as a stand-alone project, but not as a dependency. If this repository was used as a submodule and included in a different CMake project, the value of CMAKE_PROJECT_VERSION would change to the version of the other project, causing CMake to look for a VulkanHeaders package of any arbitrary version.
This PR changes the file to instead use PROJECT_VERSION. This takes on the version of the most recently called project() command, which should be the intended version given the structure of the CMakeLists.txt files in this repository.
It also updates the project version to 1.4.328, as this seems to have been missed in the commit updating the headers to this version.

Use PROJECT_VERSION instead of CMAKE_PROJECT_VERSION
