KhronosGroup/Vulkan-Utility-Libraries

BUILD.md
CMakeLists.txt
layer_utils/CMakeLists.txt
layer_utils/tests/CMakeLists.txt
layer_utils/vk_layer_settings.cpp
layer_utils/vk_layer_settings.h
scripts/CMakeLists.txt

- Updated build.md information including requirements
- Modernize CMake code
- Fix copyrights

cmake: cleanup

---

include/vulkan/layer/vk_layer_settings_ext.h

Without this fix, the profiles layer can't set the settings properly...

layer: fix const to VkLayerSettingsCreateInfoEXT

---

include/vulkan/layer/vk_layer_settings.hpp
src/layer/CMakeLists.txt
src/layer/layer_settings_manager.cpp
src/layer/vk_layer_settings_helper.cpp
tests/layer/CMakeLists.txt
tests/layer/test_setting_cpp.cpp

Makes code in the layer quite simplier.
There is still the C API the team wanted.

Add layer settings cpp

---

include/vulkan/vk_dispatch_table_helper.h
include/vulkan/vk_enum_string_helper.h
include/vulkan/vk_layer_dispatch_table.h
scripts/known_good.json

build: Update to header 1.3.258

---

scripts/known_good.json

build: Update to header 1.3.259

---

BUILD.gn
src/layer/vk_layer_settings.cpp

I have no idea what I am doing here or what I am supose to do let alone where to find information on GN...

Add GN build system

---

BUILD.gn

build: Move include dir to public config

---

include/vulkan/vk_enum_string_helper.h
scripts/known_good.json

build: Update to header 1.3.263

---

include/vulkan/vk_enum_string_helper.h
scripts/known_good.json

build: Update to header 1.3.264

---

scripts/CMakeLists.txt

cmake: Fix accidentally exporting warnings

---

include/vulkan/layer/vk_layer_settings.h
src/layer/vk_layer_settings.cpp
tests/layer/test_setting_util.cpp

New feature to cover VK_EXT_layer_settings spec review feedback

layer: Add features to list unknown settings

---

.gitattributes

git: Add .gitattributes

---

include/vulkan/layer/vk_layer_settings.h
include/vulkan/layer/vk_layer_settings.hpp
src/layer/layer_settings_manager.cpp
src/layer/layer_settings_manager.hpp
src/layer/layer_settings_util.cpp
src/layer/layer_settings_util.hpp
src/layer/vk_layer_settings.cpp
src/layer/vk_layer_settings_helper.cpp
tests/add_subdirectory/vk_layer_settings.c
tests/layer/test_setting_api.cpp
tests/layer/test_setting_cast.cpp
tests/layer/test_setting_cpp.cpp
tests/layer/test_setting_env.cpp
tests/layer/test_setting_file.cpp
tests/layer/test_setting_util.cpp

Ensure consistent usage of vku in PUBLIC header files

---

README.md
docs/vulkan_layer_settings.md

doc: Update README.md with project description

---

scripts/known_good.json

- Generate source (no changes)

build: Update to header 1.3.265

---

include/vulkan/utility/vk_struct_helper.hpp
scripts/generators/struct_helper_generator.py

Avoid multiple definition compiler error

Make GetObjectType specializations inline

---

CMakeLists.txt

cmake: Don't install .clang-format

---

scripts/known_good.json

build: Update to header 1.3.268

---

include/vulkan/utility/vk_dispatch_table.h
include/vulkan/utility/vk_struct_helper.hpp
include/vulkan/vk_enum_string_helper.h
scripts/known_good.json

build: Update to header 1.3.269

---

scripts/generate_source.py

I forgot to port to improved extension filtering code used by the generator script in my last PR.
This, again, comes from the generator script of the VVL.

scripts: Port improved extension filtering code

---

scripts/known_good.json

build: Update to header 1.3.275

---

src/vulkan/vk_safe_struct_manual.cpp

Fix to help with https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8051

safestruct: Fix null pRasterizationState

---

scripts/generate_source.py

inspired by https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/8449 (copying over other repos)

scripts: Better warning for getting reg.py

---

include/vulkan/utility/vk_dispatch_table.h
include/vulkan/utility/vk_safe_struct.hpp
include/vulkan/utility/vk_struct_helper.hpp
include/vulkan/vk_enum_string_helper.h
scripts/generators/safe_struct_generator.py
scripts/known_good.json
src/vulkan/vk_safe_struct_ext.cpp
src/vulkan/vk_safe_struct_utils.cpp

My attempt to update the headers here @mikes-lunarg (so I can target my VVL changes at least somewhere public for short term (aka my fork)) ... if this is good, happy to merge this also

build: Update to header 1.3.296

---

scripts/generators/base_generator.py
scripts/generators/vulkan_object.py

some minor fixes added to VVL version of these two files (...yes, one day will get these moved to Vulkan-Headers instead)
luckily no code gen changes so things are simple (for now)

scripts: Sync up base generator and vulkan object

---

scripts/generators/struct_helper_generator.py

@jeremyg-lunarg you can do this to CDL now as well

scripts: Remove Protect workaround
